name = clct_compat
title = ComponentsLib-CraftTools Compatibility
description = Mod that allows dynamic creation of components and tools via material definitions
optional_depends = default
depends = component_lib, crafttools
author = Mindcool25
